name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest

    - name: Update deployment image
      run: |
        sed -i "s|image: bobbyiliev/nginx-hello:latest|image: ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest|g" k8s/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Wait for deployment
      run: |
        kubectl rollout restart deployment/nginx-deployment
        kubectl rollout status deployment/nginx-deployment

    - name: Setup iptables forwarding
      run: |
        # Get minikube IP
        MINIKUBE_IP=$(minikube ip)

        # Remove any existing rule for port 8080
        sudo iptables -t nat -D PREROUTING -p tcp --dport 8080 -j DNAT --to-destination ${MINIKUBE_IP}:30080 2>/dev/null || true

        # Add new forwarding rule
        sudo iptables -t nat -A PREROUTING -p tcp --dport 8080 -j DNAT --to-destination ${MINIKUBE_IP}:30080

        # Enable forwarding if not already enabled
        echo 1 | sudo tee /proc/sys/net/ipv4/ip_forward

        # Test it works
        sleep 3
        curl http://localhost:8080
