name: Build and Push Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest .

    - name: Push Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest

    - name: Update deployment image
      run: |
        sed -i "s|image: bobbyiliev/nginx-hello:latest|image: ${{ secrets.DOCKER_USERNAME }}/nginx-hello:latest|g" k8s/deployment.yaml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
        kubectl apply -f k8s/ingress.yaml
        kubectl apply -f k8s/hpa.yaml

    - name: Wait for deployment
      run: |
        kubectl rollout restart deployment/nginx-deployment
        kubectl rollout status deployment/nginx-deployment

    - name: Setup port forwarding
      run: |
        # Kill any existing port-forward on 8080
        pkill -f "port-forward.*8080" || true
        sleep 2
        
        # Start kubectl port-forward in background
        nohup kubectl port-forward --address=0.0.0.0 service/nginx-service 8080:80 > /tmp/port-forward.log 2>&1 &
        disown
        
        # Wait for port-forward to start
        sleep 5
        
        # Test it works
        curl http://localhost:8080
